name: "HR News (Fixed Sections, No Keywords)"

on:
  workflow_dispatch:
  schedule:
    # GitHub Actions 使用 UTC，这里设为每天 23:30 UTC = 北京时间次日 07:30
    - cron: "30 23 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 urllib3

      - name: Run HR news
        env:
          # —— 时间策略：脚本内部已固定“抓昨天” —— 
          AUTO_RANGE: "true"

          # —— 抓取参数 —— 
          PAGES: "3"
          LIMIT: "60"
          DELAY: "0.8"

          # —— 非 auto-range 时的回落窗口（可选）——
          # AUTO_RANGE: "false"
          # WINDOW_HOURS: "168"

          # —— 允许无时间也展示，避免解析不到时间导致空列表 —— 
          ALLOW_NODATE: "true"

          # —— 钉钉（A 版 Secrets）——
          DINGTALK_WEBHOOKA: ${{ secrets.DINGTALK_WEBHOOKA }}
          DINGTALK_SECRETA:  ${{ secrets.DINGTALK_SECRETA }}

          NO_PUSH: "false"
        run: |
          # 关闭代理，避免被 runner 环境干扰
          unset http_proxy https_proxy all_proxy HTTP_PROXY HTTPS_PROXY ALL_PROXY NO_PROXY
          set -e

          echo "[Info] Python: $(python --version)"
          echo "[Info] Now (UTC): $(date -u '+%Y-%m-%d %H:%M:%S')"
          echo "[Info] Target push window: 07:30 (Asia/Shanghai)"

          ls -la

          CMD="python hr_news_auto_range.py --pages \"${PAGES}\" --delay \"${DELAY}\" --limit \"${LIMIT}\""
          if [ "${AUTO_RANGE}" = "true" ]; then
            # 按脚本逻辑：恒定“抓昨天”，无需额外参数
            CMD="${CMD} --auto-range"
          else
            CMD="${CMD} --window-hours \"${WINDOW_HOURS:-48}\""
          fi
          if [ "${ALLOW_NODATE}" = "true" ]; then
            CMD="${CMD} --allow-nodate"
          fi
          if [ "${NO_PUSH}" = "true" ]; then
            CMD="${CMD} --no-push"
          fi

          echo "[Run] ${CMD}"
          eval ${CMD} | tee hr_news.log

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: hr-news-results
          path: |
            hr_news.log
            hr_news.md
          if-no-files-found: ignore
