name: "People Search (Today Only)"

on:
  workflow_dispatch:
  schedule:
    - cron: "15 1 * * *"   # 每天 09:15 CST (UTC+8)

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 urllib3

      # 说明：如果 people_search_today.py 已在仓库根目录，就不需要写入脚本这一步
      # - name: Write script (如果你需要把脚本写入 runner，再启用这一段)
      #   run: |
      #     cat > people_search_today.py <<'PY'
      #     # 把完整 Python 脚本粘在这里（不要留占位注释）
      #     PY

      - name: Run people search
        env:
          KEYWORD: "外包"
          PAGES: "1"
          DELAY: "1.0"
          LIMIT: "50"

          # 钉钉：在仓库 Settings → Secrets and variables → Actions 中配置
          DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
          DINGTALK_SECRET:  ${{ secrets.DINGTALK_SECRET }}

          NO_PUSH: "false"   # 只有填 "true" 才不推送
        run: |
          unset http_proxy https_proxy all_proxy HTTP_PROXY HTTPS_PROXY ALL_PROXY NO_PROXY
          set -e

          # 如果你的脚本参数名是 --q / --pages / --delay / --limit / --no-push，请按需调整
          CMD="python people_search_today.py \
            --q \"${KEYWORD}\" \
            --pages \"${PAGES}\" \
            --delay \"${DELAY}\" \
            --limit \"${LIMIT}\""

          if [ "${NO_PUSH}" = "true" ]; then
            CMD="${CMD} --no-push"
          fi

          echo "[Run] ${CMD}"
          eval ${CMD} | tee people_search.log

      - name: Upload artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: people-search-results
          path: |
            people_search.log
          if-no-files-found: ignore
