name: HR Search (Yesterday Only)

on:
  workflow_dispatch:
  schedule:
    - cron: "15 1 * * *"   # 每天 09:15 CST 运行（UTC+8）

# 防止并发重叠
concurrency:
  group: hr-search-yesterday
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 urllib3

      # 可选：打印环境与代理，便于排错
      - name: Debug env
        run: |
          date -u
          env | grep -i proxy || true

      - name: Run HR search (yesterday only)
        env:
          # —— 业务参数（按需改这里）——
          QUERY: "外包"            # 关键词
          DATE: "yesterday"        # 只抓“昨天”；也可写成 2025-09-15
          PAGES: "2"               # 每站翻页数
          LIMIT: "50"              # 输出条数上限
          DELAY: "0.5"             # 请求间隔（秒）

          # —— 钉钉机器人（使用仓库 Secrets）——
          DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
          DINGTALK_SECRET:  ${{ secrets.DINGTALK_SECRET }}

          # 只打印不推送（调试时可设为 "true"）
          NO_PUSH: "false"
        run: |
          # 清理代理，避免被代理干扰
          unset http_proxy https_proxy all_proxy HTTP_PROXY HTTPS_PROXY ALL_PROXY NO_PROXY
          set -e

          # 组织命令（根据 NO_PUSH 决定是否加 --no-push）
          CMD="python hr_search_24h_dingtalk.py \
            --q \"${QUERY}\" \
            --pages \"${PAGES}\" \
            --delay \"${DELAY}\" \
            --limit \"${LIMIT}\" \
            --date \"${DATE}\""

          if [ "${NO_PUSH}" = "true" ]; then
            CMD="${CMD} --no-push"
          fi

          echo "[Run] ${CMD}"
          eval ${CMD}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hr-search-yesterday
          path: |
            people_search_*.csv
            people_search_*.json
