name: "HR News (Fixed Sections, No Keywords)"

on:
  workflow_dispatch:
  schedule:
    - cron: "15 1 * * *"  # 每天 09:15 CST (UTC+8)

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 urllib3

      - name: Run HR news (Mon=last 3 days, else=yesterday)
        env:
          # —— 自动范围：非周一=昨天；周一=近 N 天 ——
          AUTO_RANGE: "true"
          DAYS_FOR_MONDAY: "3"

          # —— 抓取参数 ——
          PAGES: "3"
          LIMIT: "50"
          DELAY: "1.0"

          # —— 钉钉（注意：用带 A 的 Secrets 名称）——
          DINGTALK_WEBHOOKA: ${{ secrets.DINGTALK_WEBHOOKA }}
          DINGTALK_SECRETA:  ${{ secrets.DINGTALK_SECRETA }}

          # 设为 "true" 才不推送；默认会推送
          NO_PUSH: "false"
        run: |
          unset http_proxy https_proxy all_proxy HTTP_PROXY HTTPS_PROXY ALL_PROXY NO_PROXY
          set -e
          ls -la   # 确认 hr_news_auto_range.py 在根目录
          CMD="python hr_news_auto_range.py \
            --pages \"${PAGES}\" \
            --delay \"${DELAY}\" \
            --limit \"${LIMIT}\" \
            --auto-range --days-for-monday \"${DAYS_FOR_MONDAY}\""
          if [ "${NO_PUSH}" = "true" ]; then
            CMD="${CMD} --no-push"
          fi
          echo "[Run] ${CMD}"
          eval ${CMD} | tee hr_news.log

      - name: Upload artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: hr-news-results
          path: |
            hr_news.log
            hr_news.md
          if-no-files-found: ignore
