name: People Search (Today Only)

on:
  workflow_dispatch:
  schedule:
    - cron: "15 1 * * *"   # 每天 09:15 CST

jobs:
  run:
    runs-on: ubuntu-latest

    # 可选：避免并发重叠运行
    concurrency:
      group: people-search-today
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 urllib3

      # （可选）打印时间/代理，便于排错
      - name: Debug env
        run: |
          date -u
          env | grep -i proxy || true

      - name: Run people search
      env:
  QUERY: "外包"
  DATE: "yesterday"    # 或写成 2025-09-15
  PAGES: "2"
  LIMIT: "50"
  DELAY: "0.5"
  DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
  DINGTALK_SECRET:  ${{ secrets.DINGTALK_SECRET }}

        
          # 如只打印不推送，将下行设为 "true"
          NO_PUSH: "false"
        run: |
          # 清理代理，避免被代理干扰
          unset http_proxy https_proxy all_proxy HTTP_PROXY HTTPS_PROXY ALL_PROXY NO_PROXY
          set -e

          # 组织命令（根据 NO_PUSH 决定是否加 --no-push）
          CMD="python people_search_today.py \
            --q \"${QUERY}\" \
            --pages \"${PAGES}\" \
            --window-hours \"${WINDOW_HOURS}\" \
            --delay \"${DELAY}\" \
            --limit \"${LIMIT}\""

          if [ "${NO_PUSH}" = "true" ]; then
            CMD="${CMD} --no-push"
          fi

          echo "[Run] ${CMD}"
          eval ${CMD}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: people-search-results
          path: |
            people_search_*.csv
            people_search_*.json
