- name: Run
  env:
    # —— 自动范围：非周一=昨天；周一=近 N 天 ——
    AUTO_RANGE: "true"
    DAYS_FOR_MONDAY: "3"

    # —— 抓取参数 ——
    PAGES: "3"
    LIMIT: "50"
    DELAY: "1.0"

    # —— 钉钉 —— 
    DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
    DINGTALK_SECRET:  ${{ secrets.DINGTALK_SECRET }}

    NO_PUSH: "false"
  run: |
    unset http_proxy https_proxy all_proxy HTTP_PROXY HTTPS_PROXY ALL_PROXY NO_PROXY
    set -e
    CMD="python hr_news_auto_range.py --pages \"${PAGES}\" --delay \"${DELAY}\" --limit \"${LIMIT}\" --auto-range --days-for-monday \"${DAYS_FOR_MONDAY}\""
    if [ "${NO_PUSH}" = "true" ]; then CMD="${CMD} --no-push"; fi
    echo "[Run] ${CMD}"
    eval ${CMD}
