name: People Search (Today Only)

on:
  workflow_dispatch:
  schedule:
    - cron: "15 1 * * *"   # 每天 09:15 CST

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 urllib3

      # （可选）打印时间/代理，便于排错
      - name: Debug env
        run: |
          date -u
          env | grep -i proxy || true

      - name: Run people search
        env:
          # 如果你要改关键词/页数/延迟，在这里改
          KEYWORD: "外包"
          PAGES: "1"
          DELAY: "120"
        run: |
          unset http_proxy https_proxy all_proxy HTTP_PROXY HTTPS_PROXY ALL_PROXY NO_PROXY
          python people_search_today.py --keyword "$KEYWORD" --pages "$PAGES" --delay "$DELAY" --save both

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: people-search-results
          path: |
            people_search_*.csv
            people_search_*.json
