name: "HR News (Fixed Sections, No Keywords)"

on:
  workflow_dispatch:
  schedule:
    - cron: "15 1 * * *"  # 每天 09:15 CST (UTC+8)

jobs:
  run:
    # 如果你换成国内自托管 Runner，请把这一行改成：runs-on: [self-hosted, linux, cn]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 urllib3

      - name: Write script
        run: |
          cat > hr_news_auto_range.py <<'PY'
          # 这里粘贴上面整段 Python 脚本的内容
          PY

      - name: Run
        env:
          AUTO_RANGE: "true"        # 非周一=昨天，周一=近3天
          DAYS_FOR_MONDAY: "3"
          DATE: ""                  # 如需指定某天：2025-09-17 或 yesterday
          PAGES: "2"
          LIMIT: "50"
          DELAY: "0.8"
          DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOKA }}
          DINGTALK_SECRET:  ${{ secrets.DINGTALK_SECRETA }}
          NO_PUSH: "false"
        run: |
          unset http_proxy https_proxy all_proxy HTTP_PROXY HTTPS_PROXY ALL_PROXY NO_PROXY
          python hr_news_auto_range.py --auto-range --days-for-monday "${DAYS_FOR_MONDAY}" --pages "${PAGES}" --delay "${DELAY}" --limit "${LIMIT}" ${DATE:+--date "$DATE"} ${NO_PUSH:+--no-push}

      - name: Upload artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: hr-news-results
          path: |
            *.html
            *.log
